import type { StylePreset, StyleSettings } from './types';

export const PRESETS: Record<string, StylePreset> = {
  Original: {
    name: 'Original',
    values: {
      autoRotate: false,
      fov: 52,
      minDistance: 1.2,
      maxDistance: 24,
      autoRotateSpeed: 0.3,
      splatScale: 1.08,
      opacity: 1,
      contrast: 1.24,
      brightness: 1.02,
      gamma: 1,
      saturation: 1.08,
      monochrome: false,
      invert: false,
      fogDensity: 0,
      fogNear: 0.4,
      fogFar: 1.3,
      edgeFadeStrength: 0,
      edgeFadeDistance: 0.75,
      horizonHaze: 0,
      cloudOpacity: 0,
      cloudSpeed: 0.03,
      cloudScale: 1.2,
      backgroundColor: '#d5ccb8',
      highlightTint: '#ffffff',
      shadowTint: '#8d826f',
      vignetteStrength: 0,
      grainStrength: 0,
      bloomStrength: 0,
      showAtmosphereLayers: false,
      posterize: 0,
    },
  },
  Ink: {
    name: 'Ink',
    values: {
      autoRotate: false,
      fov: 52,
      minDistance: 1.2,
      maxDistance: 24,
      autoRotateSpeed: 0.35,
      splatScale: 1.05,
      opacity: 0.95,
      contrast: 1.45,
      brightness: 0.95,
      gamma: 1.05,
      saturation: 0.2,
      monochrome: true,
      invert: false,
      fogDensity: 0.28,
      fogNear: 0.5,
      fogFar: 1.45,
      edgeFadeStrength: 0.55,
      edgeFadeDistance: 0.78,
      horizonHaze: 0.22,
      cloudOpacity: 0.2,
      cloudSpeed: 0.03,
      cloudScale: 1.2,
      backgroundColor: '#101010',
      highlightTint: '#f2f2f2',
      shadowTint: '#0a0a0a',
      vignetteStrength: 0.37,
      grainStrength: 0.05,
      bloomStrength: 0.08,
      showAtmosphereLayers: true,
      posterize: 0.16,
    },
  },
  Paper: {
    name: 'Paper',
    values: {
      autoRotate: false,
      fov: 52,
      minDistance: 1.2,
      maxDistance: 24,
      autoRotateSpeed: 0.3,
      splatScale: 1,
      opacity: 0.88,
      contrast: 0.95,
      brightness: 1.07,
      gamma: 1,
      saturation: 0.25,
      monochrome: true,
      invert: false,
      fogDensity: 0.34,
      fogNear: 0.35,
      fogFar: 1.35,
      edgeFadeStrength: 0.52,
      edgeFadeDistance: 0.72,
      horizonHaze: 0.28,
      cloudOpacity: 0.15,
      cloudSpeed: 0.025,
      cloudScale: 1.05,
      backgroundColor: '#ece8df',
      highlightTint: '#f7f5ef',
      shadowTint: '#7c7770',
      vignetteStrength: 0.18,
      grainStrength: 0.04,
      bloomStrength: 0.05,
      showAtmosphereLayers: true,
      posterize: 0.06,
    },
  },
  Fog: {
    name: 'Fog',
    values: {
      autoRotate: false,
      fov: 50,
      minDistance: 1,
      maxDistance: 26,
      autoRotateSpeed: 0.2,
      splatScale: 1.08,
      opacity: 0.78,
      contrast: 0.9,
      brightness: 1.05,
      gamma: 0.95,
      saturation: 0.15,
      monochrome: true,
      invert: false,
      fogDensity: 0.62,
      fogNear: 0.2,
      fogFar: 1.15,
      edgeFadeStrength: 0.74,
      edgeFadeDistance: 0.56,
      horizonHaze: 0.48,
      cloudOpacity: 0.35,
      cloudSpeed: 0.05,
      cloudScale: 1.45,
      backgroundColor: '#d5d5d5',
      highlightTint: '#f8f8f8',
      shadowTint: '#6f7274',
      vignetteStrength: 0.16,
      grainStrength: 0.03,
      bloomStrength: 0.12,
      showAtmosphereLayers: true,
      posterize: 0,
    },
  },
  'Night Editorial': {
    name: 'Night Editorial',
    values: {
      autoRotate: true,
      fov: 49,
      minDistance: 1.4,
      maxDistance: 22,
      autoRotateSpeed: 0.22,
      splatScale: 1,
      opacity: 0.93,
      contrast: 1.32,
      brightness: 0.92,
      gamma: 1.08,
      saturation: 0.18,
      monochrome: true,
      invert: false,
      fogDensity: 0.42,
      fogNear: 0.45,
      fogFar: 1.3,
      edgeFadeStrength: 0.68,
      edgeFadeDistance: 0.7,
      horizonHaze: 0.3,
      cloudOpacity: 0.25,
      cloudSpeed: 0.04,
      cloudScale: 1.3,
      backgroundColor: '#06080d',
      highlightTint: '#e6edf7',
      shadowTint: '#0a0d17',
      vignetteStrength: 0.42,
      grainStrength: 0.06,
      bloomStrength: 0.18,
      showAtmosphereLayers: true,
      posterize: 0.12,
    },
  },
  Sketch: {
    name: 'Sketch',
    values: {
      autoRotate: false,
      fov: 54,
      minDistance: 1,
      maxDistance: 28,
      autoRotateSpeed: 0.3,
      splatScale: 0.9,
      opacity: 0.82,
      contrast: 1.38,
      brightness: 1,
      gamma: 1.02,
      saturation: 0,
      monochrome: true,
      invert: false,
      fogDensity: 0.38,
      fogNear: 0.42,
      fogFar: 1.32,
      edgeFadeStrength: 0.6,
      edgeFadeDistance: 0.66,
      horizonHaze: 0.2,
      cloudOpacity: 0.18,
      cloudSpeed: 0.035,
      cloudScale: 1.1,
      backgroundColor: '#efefef',
      highlightTint: '#ffffff',
      shadowTint: '#4a4a4a',
      vignetteStrength: 0.26,
      grainStrength: 0.08,
      bloomStrength: 0.03,
      showAtmosphereLayers: true,
      posterize: 0.25,
    },
  },
};

export const DEFAULT_PRESET = 'Original';

export const PRESET_NAMES = Object.keys(PRESETS);

export const buildSettingsFromPreset = (name: string): StyleSettings => {
  const fallback = PRESETS[DEFAULT_PRESET];
  const selected = PRESETS[name] ?? fallback;
  return {
    preset: selected.name,
    ...selected.values,
  };
};
